name: Help request
description: Ask a question to receive help.
title: "[HELP]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        If you are experiencing unexpected behavior, please consider submitting a bug report instead.
  - type: textarea
    id: description
    attributes:
      label: How can we help?
      description: |
        Links? References? Anything that will give us more context about your question!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true